### ISSUE TITLE
esp32 support

### ISSUE THREAD

**Issue by kc5uvc** [tony-fav/esphome-sync#1]
Hello sir!  

Wonderful code.  Have really enjoyed playing around with it on an ESP8266 board, but I need to move it to an ESP32 board.  My goals are to support both DDP and e1.31, using them to control a set of relays.  I basically have it working in the 8266 environment, but I also have some sensors I am monitoring and have exceeding the boards capability.  That is why I am moving to ESP32.  However, I am running into all sorts of errors when trying to compile.  Do you have an example of this in ESP32?  Feel free to email me at charles@jonesknows.com if you would like to take this offline.  I would really like to engage you in this project.

**Comment by tony-fav** [comment]
I believe the ESP32 requires different libraries than those included for 8266. If you post the yaml you are trying, I can take a look

**Comment by kc5uvc** [comment]
esphome:
  name: xxxxxx
  libraries:
    - ESPAsyncE131
  includes:
    - e131.h

esp32:
  board: esp32dev
  framework:
    type: arduino

**Comment by kc5uvc** [comment]
Other than the logging, api, ota, and wifi sections, that is all I have in the code.  With the libraries and includes, the code compiles fine.  As soon as I add those, I start getting errors.  One of the errors references ESPAsyncUDP, however, it appears that the ESPAsyncE131 calls for that library.  So I'm really confused as to what is going on.

**Comment by kc5uvc** [comment]
Any other thoughts on this?  I would really like to get this working.

**Comment by tony-fav** [comment]
So, there seems to be some issue in the dependencies even though they state ESP32 support. But I looked back through Discord when I was testing these things, and we had a working solution for ESP32 using the built in ESPHome light partition

```yaml
esphome:
  name: esp32test
  board: esp32dev
  platform: ESP32

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "wittyfakepassword"

ota:
  password: "wittyfakepassword"


wifi:
  ssid: "hilariousssid"
  password: "wittyfakepassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dimmer1 Fallback Hotspot"
    password: "wittyfakepassword"

captive_portal:

# Enable Web server.
web_server:
  port: 80

#e131:
#  method: unicast
  
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Dimmer1 IP
    ssid:
      name: Dimmer1 SSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Dimmer1 Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Dimmer1 WiFi Signal
    update_interval: 60s

switch:
  # Switch to restart the board.
  - platform: restart
    name: Dimmer1 Restart

output:
  - platform: ac_dimmer
    id: dimmer1
    method: leading
    gate_pin: GPIO13
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer2
    method: leading
    gate_pin: GPIO16
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer3
    method: leading
    gate_pin: GPIO17
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer4
    method: leading
    gate_pin: GPIO21
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer5
    method: leading
    gate_pin: GPIO22
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer6
    method: leading
    gate_pin: GPIO32
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer7
    method: leading
    gate_pin: GPIO25
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
  - platform: ac_dimmer
    id: dimmer8
    method: leading
    gate_pin: GPIO27
    zero_cross_pin:
      number: GPIO4
      mode: INPUT
      inverted: yes
      
e131:
  method: multicast # default: register E1.31 to Multicast group

light:
  - platform: partition
    name: "Addressable Dimmerized Lights"
    segments:
      - single_light_id: strand1
      - single_light_id: strand2
      - single_light_id: strand3
      - single_light_id: strand4
      - single_light_id: strand5
      - single_light_id: strand6
      - single_light_id: strand7
      - single_light_id: strand8
    effects:
      - e131:
          universe: 1
          channels: MONO

  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
    id: strand1
  - platform: monochromatic
    output: dimmer2
    name: Dimmerized Light2
    id: strand2
  - platform: monochromatic
    output: dimmer3
    name: Dimmerized Light3
    id: strand3
  - platform: monochromatic
    output: dimmer4
    name: Dimmerized Light4
    id: strand4
  - platform: monochromatic
    output: dimmer5
    name: Dimmerized Light5
    id: strand5
  - platform: monochromatic
    output: dimmer6
    name: Dimmerized Light6
    id: strand6
  - platform: monochromatic
    output: dimmer7
    name: Dimmerized Light7
    id: strand7
  - platform: monochromatic
    output: dimmer8
    name: Dimmerized Light8
    id: strand8
```

This same approach can be used for the built in "WLED Effect" in ESPHome which enables DDP control (https://esphome.io/components/light/index.html?highlight=wled#wled-effect)
